### ISSUE TITLE
Change clicks to cookies

### ISSUE THREAD

**Issue by Jonchu650** [ZombieNW/ZombieNW.github.io#1]
on cookie.html where you buy an auto clicker/grandma, use (50/100 cookies) instead of clicks

**Comment by Jonchu650** [comment]
![Screenshot 2020-12-15 at 11 50 57 AM](https://user-images.githubusercontent.com/68526622/102265804-74dfb300-3ecc-11eb-8981-55cb228eb628.png) Im so addicted

**Comment by ZombieNW** [comment]
i-, fine
